name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Prepare
        run: |
          cp .env.example .env
          pnpm run db:generate
        
      - name: TypeScript type checking
        run: pnpm typecheck

      - name: Linting
        run: pnpm lint

      - name: Build
        run: pnpm build
