name: Deploy

on:
  push:
    branches:
      - chore/deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: npm install, build, and test
        run: |
          pnpm i
          cp .env.example .env # an env file is needed for `build`
          pnpm run db:generate
          pnpm build

          # we want to delete the node_modules, as they will also contain `devDependencies`
          # Note: `pnpm prune --prod` is not enough, as that will keep all dev dependencies installed inside `node_modules/.pnpm`
          rm -rf node_modules/ 

          # This will install all "dependencies" (excluding "devDependencies")
          pnpm i --prod
          rm .env
      - name: Zip artifact for deployment
        # `-y`: means preserve symlinks. 
        # `./*`: the current directory
        # `.next`: explicitly also zip this hidden directory. 
        # `-r`: recursive
        run: zip -y release.zip ./* .next -r 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech-survey-web'
          slot-name: 'production'
          package: .
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
